### ISSUE TITLE
v3.7.0 is not backwards compatible when using references

### ISSUE THREAD

**Issue by bretrzaun** [doctrine/DoctrineFixturesBundle#466]
### Bug Report

Error when executing fixtures after upgrading to v3.7.0:
```
In AbstractFixture.php line 78:
                                                                                                                                                                                        
  Too few arguments to function Doctrine\Common\DataFixtures\AbstractFixture::getReference(), 1 passed in
```

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3.7.0
| Previous Version if the bug is a regression | 3.6.2

#### Summary

Fixture creation is not running successfully.

#### Current behavior

see error message above

#### Expected behavior

No error - since it's only a minor version upgrade.

#### How to reproduce

Run a migration having a `$this->getReference('user')` call with only one parameter - which was fine until now.

**Comment by greg0ire** [comment]
Did you upgrade only the bundle or did you also upgrade the library?

**Comment by bretrzaun** [comment]
I was only having this in my composer.json:
```
"doctrine/doctrine-fixtures-bundle": "^3.0.0",
```

now replaced with:
```
"doctrine/doctrine-fixtures-bundle": "~3.6.0",
```

**Comment by greg0ire** [comment]
Add a version constraint for the library if your fixture depends on it.

**Comment by derrabus** [comment]
Closing as this is not a bug on our side.

**Comment by ThomasLandauer** [comment]
I wrote an answer on StackOverflow: https://stackoverflow.com/a/79234035/1668200

**Comment by bmoll-axiomconnected** [comment]
> Closing as this is not a bug on our side.

@derrabus @greg0ire I understand your perspective, but I believe this issue should be reconsidered. The [official documentation for doctrine/doctrine-fixtures-bundle v3.6](https://symfony.com/bundles/DoctrineFixturesBundle/3.6.x/index.html#sharing-objects-between-fixtures) includes examples where the second parameter of `AbstractFixture::getReference()` is omitted. This implicitly suggests to users that this method can be used as shown without concern for future minor upgrades.

Snippet shown in official documentation:

```php
// src/DataFixtures/GroupFixtures.php
// ...
class GroupFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $userGroup = new Group('administrators');
        // this reference returns the User object created in UserFixtures
        $userGroup->addUser($this->getReference(UserFixtures::ADMIN_USER_REFERENCE));

        $manager->persist($userGroup);
        $manager->flush();
    }
}
```

Because the documentation presents this as the standard way to use the library, it is reasonable for users to assume that following these examples will not introduce breaking changes in a minor version update. However, with the upgrade from v3.6 to v3.7, that assumption proves incorrect, as the omission of the second parameter now results in an error.

Given that semantic versioning suggests minor updates should not introduce breaking changes, and that users relied on official documentation when implementing their fixtures, I believe this issue deserves further discussion. If doctrine/data-fixtures 2.0 introduced a breaking change, then upgrading to it should have been deferred until the next major release of doctrine/doctrine-fixtures-bundle to ensure compatibility.

**Comment by greg0ire** [comment]
> Because the documentation presents this as the standard way to use the library, it is reasonable for users to assume that following these examples will not introduce breaking changes in a minor version update.

The standard documentation shows examples written in  PHP. If it were to be affected by a breaking change in PHP, would you still complain?

**Comment by bmoll-axiomconnected** [comment]
> The standard documentation shows examples written in PHP. If it were to be affected by a breaking change in PHP, would you still complain?

@greg0ire I understand your perspective, but I don’t think this is a fair comparison. A breaking change in PHP itself is fundamentally different because upgrading a library cannot upgrade the version of PHP that is running. Library maintainers have control over which PHP versions their library supports, but users are responsible for upgrading PHP itself.

In this case, however, the doctrine/doctrine-fixtures-bundle **did** directly introduce a breaking change by upgrading a dependency to a new major version within what was supposed to be a minor release. The fact that the official documentation for v3.6 demonstrated usage that was broken by this change reinforces why users reasonably expected their code to continue working in v3.7.

I understand that this happened long enough ago that it’s not realistic to expect any changes at this point. There have been several releases since then, and retroactively altering this could introduce another set of issues. I’ll update the fixtures we’ve already written so we can upgrade, but it would be nice to know that going forward, we won’t run into unexpected breaking changes in a minor version update again.

**Comment by derrabus** [comment]
> In this case, however, the doctrine/doctrine-fixtures-bundle **did** directly introduce a breaking change by upgrading a dependency to a new major version within what was supposed to be a minor release.

That's not what happened. The bundle introduced support for a new major version. The old version is still supported.

The bundle is just a piece of glue code between the DataFixtures library and the Symfony framework. Still it's the library that you are using, so when you upgrade the library to a new major version (yes, that's what _you_ did), you need to make sure that your code is compatible with that major version.

> The fact that the official documentation for v3.6 demonstrated usage that was broken by this change reinforces why users reasonably expected their code to continue working in v3.7.

The documentation shows example code for v1 of the library because that was the only version that existed at that time. We cannot anticipate future deprecations or breaking changes.

> it would be nice to know that going forward, we won’t run into unexpected breaking changes in a minor version update again.

This will happen again to you, if you don't put version constraints on the libraries that you are using.

**Comment by greg0ire** [comment]
@bmoll-axiomconnected please consider using https://github.com/maglnet/ComposerRequireChecker . It will let you know what's wrong with your requirements, and will spare you similar issues with other packages.
